import type { PresetId, Pump, ValveId, ValveKind, ValveState } from "./types";

export const VALVE_META: Record<
  ValveId,
  {
    title: string;
    type: ValveKind;
    rating: "5K" | "10K";
    system: string;
    desc: string;
  }
> = {
  "C-1": {
    title: "Well isolation",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "RCD / annular outlet into P-4-E-C. Isolates the well from the dual-choke package.",
  },
  "C-2": {
    title: "RCD bleed",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "Bleed from the RCD / flow-line drop.",
  },
  "C-3": {
    title: "Ck-A upstream",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "Isolates Choke A from the inlet header. Must be open for Ck-A service.",
  },
  "C-4": {
    title: "Ck-A downstream",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "Isolates Choke A from the outlet header. Must be open for Ck-A service.",
  },
  "C-5": {
    title: "Equalize / bypass (upper)",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "Upper center equalize between dual-choke cross blocks. Open = choke bypass (peer to C-8).",
  },
  "C-6": {
    title: "Ck-B upstream",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "Isolates Choke B from the inlet header. Must be open for Ck-B service.",
  },
  "C-7": {
    title: "Ck-B downstream",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "Isolates Choke B from the outlet header. Must be open for Ck-B service.",
  },
  "C-8": {
    title: "Equalize / bypass (lower)",
    type: "ball",
    rating: "5K",
    system: "MPD primary",
    desc: "Lower center equalize between dual-choke cross blocks (peer to C-5). Open = choke bypass. Not in the Ck-B loop.",
  },
  "D-1": {
    title: "FM-01 inlet",
    type: "ball",
    rating: "5K",
    system: "MPD discharge",
    desc: "Upstream isolation of the Coriolis. Must be open for FM-01 to see returns.",
  },
  "D-2": {
    title: "FM-01 outlet",
    type: "ball",
    rating: "5K",
    system: "MPD discharge",
    desc: "Downstream isolation of the Coriolis meter.",
  },
  "D-3": {
    title: "Meter bypass",
    type: "ball",
    rating: "5K",
    system: "MPD discharge",
    desc: "Opens the bypass around FM-01. Meter will not see full returns.",
  },
  "D-4": {
    title: "Returns to flow line",
    type: "ball",
    rating: "5K",
    system: "MPD discharge",
    desc: "On the D-5 run. Open with D-5 to dump returns to the flow line; close to send them to the MGS via D-6.",
  },
  "D-5": {
    title: "Returns to flow line",
    type: "gate",
    rating: "5K",
    system: "MPD discharge",
    desc: "Paired with D-4. Open both to route package returns to the rig flow line instead of the MGS.",
  },
  "D-6": {
    title: "MGS inlet",
    type: "ball",
    rating: "5K",
    system: "MPD discharge",
    desc: "Last isolation into the mud-gas separator.",
  },
  "E-1": {
    title: "Fill-up strainer",
    type: "gate",
    rating: "5K",
    system: "Equalization",
    desc: "Basket strainer on the trip-tank fill-up into the RCD.",
  },
  "E-2": {
    title: "Fill-up check",
    type: "check",
    rating: "5K",
    system: "Equalization",
    desc: "Check on the fill-up drop. Prevents backflow from the RCD into the trip tank.",
  },
  "E-3": {
    title: "Fill-up",
    type: "gate",
    rating: "5K",
    system: "Equalization",
    desc: "Trip-tank fill-up isolation into the RCD bowl.",
  },
  "E-4": {
    title: "To rig manifold",
    type: "ball",
    rating: "10K",
    system: "Equalization",
    desc: "Crossover from the MPD header down to the rig choke manifold.",
  },
  "E-5": {
    title: "Choke-line isolation",
    type: "gate",
    rating: "10K",
    system: "Equalization",
    desc: "Well-control template: isolation on the choke line from the spool into the rig manifold. Kill-line template: isolation on the kill line into the spool.",
  },
  "E-6": {
    title: "E-4 drop isolation",
    type: "gate",
    rating: "10K",
    system: "Equalization",
    desc: "Stacked gate on the E-4 drop into E-5 / the rig manifold inlet.",
  },
  "S-1": {
    title: "Standpipe header (left)",
    type: "gate",
    rating: "5K",
    system: "Standpipe",
    desc: "Header gate between T1 and T2. Close to isolate T1 from the rest of the manifold.",
  },
  "S-2": {
    title: "Standpipe header (mid)",
    type: "gate",
    rating: "5K",
    system: "Standpipe",
    desc: "Header gate between T2 and the drill-string takeoff. T1/T2 need this open to go downhole.",
  },
  "S-3": {
    title: "SPP bleed",
    type: "gate",
    rating: "5K",
    system: "Standpipe",
    desc: "Right-hand header gate to the SPP bleed-off line.",
  },
  "S-4": {
    title: "Kill wing",
    type: "gate",
    rating: "5K",
    system: "Standpipe",
    desc: "Hanging gate on the kill line. Must be open to pump down the kill line.",
  },
  "S-5": {
    title: "Standpipe spare",
    type: "gate",
    rating: "5K",
    system: "Standpipe",
    desc: "Spare hanging gate on a dead-leg stub.",
  },
  "S-6": {
    title: "Drill string",
    type: "gate",
    rating: "5K",
    system: "Standpipe",
    desc: "Hanging gate to the drill string. Must be open to circulate downhole.",
  },
  "S-7": {
    title: "SPP bleed isolation",
    type: "gate",
    rating: "5K",
    system: "Standpipe",
    desc: "Gate between S-3 and the SPP bleed-off line. Close to isolate bleed-off from the standpipe header.",
  },
  "F-1": {
    title: "Flow line to shakers (upper)",
    type: "gate",
    rating: "5K",
    system: "Flow line",
    desc: "Upper stacked gate on the rig flow line riser to the shakers.",
  },
  "F-2": {
    title: "Flow line to shakers (lower)",
    type: "gate",
    rating: "5K",
    system: "Flow line",
    desc: "Lower stacked gate on the rig flow line riser to the shakers.",
  },
  "F-3": {
    title: "MGS to flow line",
    type: "gate",
    rating: "5K",
    system: "Flow line",
    desc: "Lateral from the MGS liquid outlet into the rig flow line.",
  },
  "F-4": {
    title: "Flow line to MGS",
    type: "gate",
    rating: "5K",
    system: "Flow line",
    desc: "Lateral from the rig flow line back to the MGS.",
  },
  "F-5": {
    title: "D-5 lateral",
    type: "gate",
    rating: "5K",
    system: "Flow line",
    desc: "Gate on the D-5 / spec-break lateral off the flow line.",
  },
  "F-6": {
    title: "Flow-line check",
    type: "check",
    rating: "5K",
    system: "Flow line",
    desc: "Check on the D-5 lateral. Prevents backflow into the flow line.",
  },
  "T-1": {
    title: "Trip tank to flow line",
    type: "gate",
    rating: "5K",
    system: "Trip tank",
    desc: "Right-hand trip-tank isolation into the rig flow line.",
  },
  "T-2": {
    title: "Trip tank fill-up",
    type: "gate",
    rating: "5K",
    system: "Trip tank",
    desc: "Left-hand trip-tank isolation into the RCD fill-up train.",
  },
  "B-1": {
    title: "Kill HCR",
    type: "gate",
    rating: "10K",
    system: "BOP",
    desc: "Spool left-hand hydraulic control valve on the kill inlet.",
  },
  "B-2": {
    title: "Choke HCR",
    type: "gate",
    rating: "10K",
    system: "BOP",
    desc: "Spool right-hand hydraulic control valve on the choke outlet.",
  },
  "K-1": {
    title: "Kill-line check",
    type: "check",
    rating: "10K",
    system: "BOP",
    desc: "Check on the kill line into the spool. Kill-line template only.",
  },
  "M-0": {
    title: "Manifold inlet",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Manifold inlet isolation when E-5 is on the kill line.",
  },
  "M-1": {
    title: "Remote choke upstream",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Upstream gate on the remote (auto) choke leg.",
  },
  "M-2": {
    title: "Remote choke downstream",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Downstream gate on the remote (auto) choke leg.",
  },
  "M-3": {
    title: "Manual choke upstream",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Upstream gate on the manual choke leg.",
  },
  "M-4": {
    title: "Manual choke downstream",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Downstream gate on the manual choke leg.",
  },
  "M-5": {
    title: "To trip tank",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Manifold outlet to the trip tank.",
  },
  "M-6": {
    title: "To MGS",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Manifold outlet to the MGS.",
  },
  "M-7": {
    title: "To panic line",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Manifold outlet to the panic line.",
  },
  "M-8": {
    title: "To shakers",
    type: "gate",
    rating: "10K",
    system: "Rig manifold",
    desc: "Manifold outlet to the shakers.",
  },
};

export const DEFAULT_VALVES: Record<ValveId, ValveState> = {
  "C-1": "open",
  "C-2": "closed",
  "C-3": "open",
  "C-4": "open",
  "C-5": "closed",
  "C-6": "closed",
  "C-7": "closed",
  "C-8": "closed",
  "D-1": "open",
  "D-2": "open",
  "D-3": "closed",
  "D-4": "closed",
  "D-5": "closed",
  "D-6": "open",
  "E-1": "closed",
  "E-2": "open",
  "E-3": "closed",
  "E-4": "closed",
  "E-5": "closed",
  "S-1": "open",
  "S-2": "open",
  "S-3": "open",
  "S-4": "open",
  "S-5": "closed",
  "S-6": "open",
  "S-7": "open",
  "F-1": "open",
  "F-2": "open",
  "F-3": "open",
  "F-4": "closed",
  "F-5": "open",
  "F-6": "open",
  "T-1": "closed",
  "T-2": "closed",
  "B-1": "closed",
  "B-2": "closed",
  "K-1": "closed",
  "M-0": "closed",
  "M-1": "closed",
  "M-2": "closed",
  "M-3": "closed",
  "M-4": "closed",
  "M-5": "closed",
  "M-6": "closed",
  "M-7": "closed",
  "M-8": "closed",
  "E-6": "open",
};

export const DEFAULT_PUMPS: Pump[] = [
  { id: "T1", name: "Triplex 1", on: true, spm: 68 },
  { id: "T2", name: "Triplex 2", on: true, spm: 68 },
  { id: "T3", name: "Triplex 3", on: false, spm: 55 },
];

export const PRESETS: Record<
  PresetId,
  {
    label: string;
    blurb: string;
    valves: Record<ValveId, ValveState>;
    ckA: number;
    ckB: number;
    ckM: number;
  }
> = {
  cka: {
    label: "Circulate Ck-A",
    blurb: "Choke A in service; returns to MGS (D-6); meter in line; D-3 closed; Ck-B isolated.",
    valves: { ...DEFAULT_VALVES },
    ckA: 38,
    ckB: 0,
    ckM: 0,
  },
  ckb: {
    label: "Circulate Ck-B",
    blurb: "Choke B in service; returns to MGS (D-6); meter in line; D-3 closed; Ck-A isolated.",
    valves: {
      ...DEFAULT_VALVES,
      "C-3": "closed",
      "C-4": "closed",
      "C-6": "open",
      "C-7": "open",
    },
    ckA: 0,
    ckB: 40,
    ckM: 0,
  },
  dual: {
    label: "Dual choke",
    blurb: "Both chokes lined up in parallel; returns to MGS (D-6); meter in line; D-3 closed.",
    valves: {
      ...DEFAULT_VALVES,
      "C-6": "open",
      "C-7": "open",
    },
    ckA: 28,
    ckB: 28,
    ckM: 0,
  },
  tofl: {
    label: "To flow line",
    blurb: "Exclusive returns to flow line (D-4∧D-5); D-6 closed.",
    valves: {
      ...DEFAULT_VALVES,
      "D-4": "open",
      "D-5": "open",
      "D-6": "closed",
    },
    ckA: 38,
    ckB: 0,
    ckM: 0,
  },
  split: {
    label: "Split returns",
    blurb: "ABNORMAL — simultaneous FL + MGS. Training only.",
    valves: {
      ...DEFAULT_VALVES,
      "D-4": "open",
      "D-5": "open",
      "D-6": "open",
    },
    ckA: 38,
    ckB: 0,
    ckM: 0,
  },
  bypass: {
    label: "Meter bypass",
    blurb: "Returns around FM-01. Meter reads isolated. Exclusive MGS (D-6).",
    valves: {
      ...DEFAULT_VALVES,
      "D-3": "open",
      "D-2": "closed",
    },
    ckA: 38,
    ckB: 0,
    ckM: 0,
  },
  manifold: {
    label: "Rig manifold",
    blurb: "MPD chokes isolated. Returns via E-4∧E-5∧M-1∧M-2 to the rig choke manifold.",
    valves: {
      ...DEFAULT_VALVES,
      "C-3": "closed",
      "C-4": "closed",
      "D-4": "closed",
      "D-2": "closed",
      "D-6": "closed",
      "E-4": "open",
      "E-5": "open",
      "M-1": "open",
      "M-2": "open",
    },
    ckA: 0,
    ckB: 0,
    ckM: 35,
  },
  shutin: {
    label: "Shut in",
    blurb: "C-1 closed. Well isolated from the MPD package.",
    valves: {
      ...DEFAULT_VALVES,
      "C-1": "closed",
      "C-3": "closed",
      "C-4": "closed",
      "S-6": "closed",
    },
    ckA: 0,
    ckB: 0,
    ckM: 0,
  },
};

export const CV_MAX_AUTO = 92;
export const CV_MAX_MANIFOLD = 70;
export const GAL_PER_STROKE = 3.28;
export const ANNULAR_MAWP = 5000;
export const ESD_PSI = 4800;
export const WARN_PSI = 3200;
